### ISSUE TITLE
Feature request: Movable toggle

### ISSUE THREAD

**Issue by jakkn** [Jorteck/NWN.Toolbox#2]
The toggle can sometimes get in the way of existing dialog interfaces, as seen in the screenshot below. The toggle should preferably find a new default position with less chance of impact with other windows, and be made movable.

![image](https://user-images.githubusercontent.com/3417835/147825822-ffee884f-878f-4d16-81dd-ebd8dd23e7b4.png)

Perhaps it could live to the right of the difficulty slider where the Debug dropdown is positioned in this image
![image](https://user-images.githubusercontent.com/3417835/147826105-05342161-fc6c-43df-9977-1a6ff51a74ef.png)

**Comment by Jorteck** [comment]
Should be fixed in https://github.com/Jorteck/NWN.Toolbox/commit/5efa6b06a7afff23563ac22799bc65ea8c856fec#diff-712822a78e498f7c1e58f9c02640ada94442a8d7ed1cfdfa3a77d732a65cf25fL40-R40
